### ISSUE TITLE
Falla instalacion de api

### ISSUE THREAD

**Issue by jobiols** [odoo-arg/l10n_ar_api#1]
Buenas, parece que soy el primero en reportar!

Cuando intento instalar el api falla con este error:

(odoo-arg) jobiols@odoo:~$ sudo pip install l10n_ar_api
The directory '/home/jobiols/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jobiols/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting l10n_ar_api
  Downloading l10n_ar_api-1.0.3-py2-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 207kB/s 
Requirement already satisfied: zeep in /usr/local/lib/python2.7/dist-packages (from l10n_ar_api)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from l10n_ar_api)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from l10n_ar_api)
Collecting M2Crypto (from l10n_ar_api)
  Downloading M2Crypto-0.26.0.tar.gz (305kB)
    100% |████████████████████████████████| 307kB 896kB/s 
Collecting unidecode (from l10n_ar_api)
  Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228kB)
    100% |████████████████████████████████| 235kB 1.2MB/s 
Collecting BeautifulSoup (from l10n_ar_api)
  Downloading BeautifulSoup-3.2.1.tar.gz
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: lxml>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: requests-toolbelt>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: cached-property>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: defusedxml>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: isodate>=0.5.4 in /usr/local/lib/python2.7/dist-packages (from zeep->l10n_ar_api)
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from M2Crypto->l10n_ar_api)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->zeep->l10n_ar_api)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->zeep->l10n_ar_api)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->zeep->l10n_ar_api)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->zeep->l10n_ar_api)
Installing collected packages: M2Crypto, unidecode, BeautifulSoup, l10n-ar-api
  Running setup.py install for M2Crypto ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k9yR27/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Uy6fFn-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/six.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2crypto.py -> build/lib.linux-x86_64-2.7/M2Crypto
    creating build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    creating build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/packet.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/constants.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/SWIG
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -I/usr/include -I/usr/include/x86_64-linux-gnu -I/tmp/pip-build-k9yR27/M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -DTHREADING
    SWIG/_m2crypto_wrap.c:3541:25: fatal error: openssl/err.h: No existe el archivo o el directorio
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k9yR27/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Uy6fFn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-k9yR27/M2Crypto/

**Comment by dcrocco** [comment]
Hola Jorge, es una dependencia de M2crypto del SO, apt-get install
python-m2crypto lo va a solucionar. Si miras el archivo de Travis tiene los
paquetes de Ubuntu necesarios.

Cualquier cosa avisanos

**Comment by lbaldi** [comment]
@jobiols pudiste solucionarlo con la respuesta de Daniel?

**Comment by jobiols** [comment]
Hola, @lbaldi 

Recien estuve probando nuevamente pero ahora me falla con otra cosa:

root@5d23ecc52d58:/# pip install l10n_ar_api
Downloading/unpacking l10n-ar-api
  Downloading l10n_ar_api-1.0.3-py2-none-any.whl (56kB): 56kB downloaded
Requirement already satisfied (use --upgrade to upgrade): M2Crypto in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Downloading/unpacking BeautifulSoup (from l10n-ar-api)
  Downloading BeautifulSoup-3.2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-7wbngJ/BeautifulSoup/setup.py) egg_info for package BeautifulSoup
    
Downloading/unpacking zeep (from l10n-ar-api)
  Downloading zeep-2.4.0-py2.py3-none-any.whl (131kB): 131kB downloaded
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Downloading/unpacking unidecode (from l10n-ar-api)
  Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228kB): 228kB downloaded
Downloading/unpacking appdirs>=1.4.0 (from zeep->l10n-ar-api)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking isodate>=0.5.4 (from zeep->l10n-ar-api)
  Downloading isodate-0.5.4.tar.gz
  Running setup.py (path:/tmp/pip-build-7wbngJ/isodate/setup.py) egg_info for package isodate
    
Downloading/unpacking cached-property>=1.3.0 (from zeep->l10n-ar-api)
  Downloading cached_property-1.3.0-py2.py3-none-any.whl
Downloading/unpacking defusedxml>=0.4.1 (from zeep->l10n-ar-api)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0.0 in /usr/lib/python2.7/dist-packages (from zeep->l10n-ar-api)
Downloading/unpacking requests>=2.7.0 (from zeep->l10n-ar-api)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB): 88kB downloaded
Downloading/unpacking six>=1.9.0 (from zeep->l10n-ar-api)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking requests-toolbelt>=0.7.1 (from zeep->l10n-ar-api)
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking certifi>=2017.4.17 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB): 349kB downloaded
Downloading/unpacking idna>=2.5,<2.7 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Downloading/unpacking urllib3>=1.21.1,<1.23 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB): 132kB downloaded
Installing collected packages: l10n-ar-api, BeautifulSoup, zeep, unidecode, appdirs, isodate, cached-property, defusedxml, requests, six, requests-toolbelt, certifi, idna, chardet, urllib3
  Running setup.py install for BeautifulSoup
    
Compiling /tmp/pip-build-7wbngJ/zeep/zeep/asyncio/bindings.py ...
  File "/tmp/pip-build-7wbngJ/zeep/zeep/asyncio/bindings.py", line 8
    async def send(self, client, options, operation, args, kwargs):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-7wbngJ/zeep/zeep/asyncio/transport.py ...
  File "/tmp/pip-build-7wbngJ/zeep/zeep/asyncio/transport.py", line 48
    async def _load_remote_data_async():
            ^
SyntaxError: invalid syntax

  Running setup.py install for isodate
    
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed l10n-ar-api BeautifulSoup zeep unidecode appdirs isodate cached-property defusedxml requests six requests-toolbelt certifi idna chardet urllib3
Cleaning up...
root@5d23ecc52d58:/#
