### ISSUE TITLE
Falla instalacion de api

### ISSUE THREAD

**Issue by jobiols** [odoo-arg/l10n_ar_api#2]
Hola, @dcrocco 
Sigo sin poder instalar el api

Cuando quiero instalar termina con un error.

```
apt-get update && apt-get upgrade -y
apt-get install python-m2crypto -y
pip install l10n_ar_api

```
produce lo siguiente:
Downloading/unpacking l10n-ar-api
  Downloading l10n_ar_api-1.0.4-py2.py3-none-any.whl (57kB): 57kB downloaded
Requirement already satisfied (use --upgrade to upgrade): M2Crypto in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Downloading/unpacking BeautifulSoup (from l10n-ar-api)
  Downloading BeautifulSoup-3.2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-UuykY5/BeautifulSoup/setup.py) egg_info for package BeautifulSoup
    
Downloading/unpacking zeep (from l10n-ar-api)
  Downloading zeep-2.4.0-py2.py3-none-any.whl (131kB): 131kB downloaded
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from l10n-ar-api)
Downloading/unpacking unidecode (from l10n-ar-api)
  Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228kB): 228kB downloaded
Downloading/unpacking appdirs>=1.4.0 (from zeep->l10n-ar-api)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking isodate>=0.5.4 (from zeep->l10n-ar-api)
  Downloading isodate-0.5.4.tar.gz
  Running setup.py (path:/tmp/pip-build-UuykY5/isodate/setup.py) egg_info for package isodate
    
Downloading/unpacking cached-property>=1.3.0 (from zeep->l10n-ar-api)
  Downloading cached_property-1.3.0-py2.py3-none-any.whl
Downloading/unpacking defusedxml>=0.4.1 (from zeep->l10n-ar-api)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0.0 in /usr/lib/python2.7/dist-packages (from zeep->l10n-ar-api)
Downloading/unpacking requests>=2.7.0 (from zeep->l10n-ar-api)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB): 88kB downloaded
Downloading/unpacking six>=1.9.0 (from zeep->l10n-ar-api)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking requests-toolbelt>=0.7.1 (from zeep->l10n-ar-api)
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking certifi>=2017.4.17 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB): 349kB downloaded
Downloading/unpacking idna>=2.5,<2.7 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Downloading/unpacking urllib3>=1.21.1,<1.23 (from requests>=2.7.0->zeep->l10n-ar-api)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB): 132kB downloaded
Installing collected packages: l10n-ar-api, BeautifulSoup, zeep, unidecode, appdirs, isodate, cached-property, defusedxml, requests, six, requests-toolbelt, certifi, idna, chardet, urllib3
  Running setup.py install for BeautifulSoup
    
Compiling /tmp/pip-build-UuykY5/zeep/zeep/asyncio/bindings.py ...
  File "/tmp/pip-build-UuykY5/zeep/zeep/asyncio/bindings.py", line 8
    async def send(self, client, options, operation, args, kwargs):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-UuykY5/zeep/zeep/asyncio/transport.py ...
  File "/tmp/pip-build-UuykY5/zeep/zeep/asyncio/transport.py", line 48
    async def _load_remote_data_async():
            ^
SyntaxError: invalid syntax

  Running setup.py install for isodate
    
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed l10n-ar-api BeautifulSoup zeep unidecode appdirs isodate cached-property defusedxml requests six requests-toolbelt certifi idna chardet urllib3
Cleaning up...

Otro efecto lateral es que se rompe el pip o sea queda asi:

root@d582b274a5b3:/# pip   
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by dcrocco** [comment]
Hola Jorge, lo que vi que faltaba para solucionar los problemas que teniamos con la instalación fue agregar la siguiente dependencia (ubuntu):
- sudo apt-get install libssl-dev

No estoy seguro que solucione ese problema puntual pero fue el unico error que encontramos, querés probar y me avisas?

**Comment by jobiols** [comment]
Daniel,
Estuve probando pero todavia no me anda, lo que vi es que en ubuntu instala bien pero en debian no y la imagen docker oficial de odoo esta hecha con debian:jessie.

Sigo probando de a ratos cada vez que se me ocurre algo, Gracias.

**Comment by jobiols** [comment]
Hola @dcrocco 
Ya arregle el problema!!
Lo que pasaba era que la imagen oficial de odoo esta hecha sobre debian jessie, este tiene python 2.7.9 y el paquete zeep necesita una versión mayor de python. 
Eso era lo que fallaba así que lo cambie a debian stretch y ahora se instalo bien. 

Podes cerrar el issue, gracias por la paciencia.
